version: "3.2"
services:
  voicy:
    container_name: lehabot-node
    image: alexey/lehabot-dev
    restart: always
    command: yarn start
    working_dir: /app/lehabot
    build:
      context: .
      dockerfile: Dockerfile-base
    depends_on:
    - mongo
    external_links:
    - mongo
    volumes:
      - ..:/app/lehabot
      - ../nodemodules:/app/lehabot/node_modules

  # networks:
  #   - mongo-net

  mongo:
    container_name: mongo
    image: mongo:4.4.0
    volumes:
      - type: bind
        source: ../data/db
        target: /data/db

    ports:
      - '27017:27017'